apiVersion: v1
kind: Service
metadata:
  name: appsmith-editor
spec:
  selector:
    app: appsmith-editor
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: appsmith-editor
spec:
  selector:
    matchLabels:
      app: appsmith-editor
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: appsmith-editor
    spec:
      containers:
      - name: nginx
        image: appsmith/appsmith-editor
        # command: 
        #   - /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & /start-nginx.sh'"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: application-config
        volumeMounts:
          - name: nginx-config-template
            mountPath: /nginx.conf.template
            subPath: nginx.conf.template
      volumes:
      - name: nginx-config-template
        configMap:
          name: nginx-config-template
